# Generated by Django 3.2.4 on 2023-10-28 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_calidadpágina'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalidadPágina',
        ),
        migrations.DeleteModel(
            name='Opción',
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
    ]
